create table if not exists public.content_pages (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  slug text not null unique,
  page_path text not null unique,
  description text,
  hero_title text not null,
  hero_subtitle text,
  hero_description text,
  seo_title text,
  seo_description text,
  empty_state_title text,
  empty_state_description text,
  primary_cta_text text,
  primary_cta_href text,
  placement_slug text not null,
  sort_order integer not null default 100,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

drop trigger if exists set_content_pages_updated_at on public.content_pages;
create trigger set_content_pages_updated_at
before update on public.content_pages
for each row execute function public.set_updated_at();

insert into public.content_pages (
  title,
  slug,
  page_path,
  description,
  hero_title,
  hero_subtitle,
  hero_description,
  seo_title,
  seo_description,
  empty_state_title,
  empty_state_description,
  primary_cta_text,
  primary_cta_href,
  placement_slug,
  sort_order,
  is_active
)
values
  (
    '资源库',
    'resources',
    '/resources',
    '海外 AI 工具、教程、工作流和资源入口的总索引。',
    '海外 AI 资源筛选库',
    'CURATED AI RESOURCE LIBRARY',
    '这里不是简单堆链接，而是按普通人、内容创作者、AI 工具玩家和副业创业者的真实场景，筛选可上手的 AI 工具、知识库、创作工具和工作流入口。',
    'AI 资源库',
    '收录海外 AI 工具、AI 搜索、知识库、图片视频生成、语音配音和工作流资源，适合普通人、创作者和副业创业者长期收藏。',
    '暂无资源',
    '管理员可以进入后台“内容发布”，选择发布位置“资源库”后，这里会自动展示。',
    '发布资源',
    '/admin?section=content-publish',
    'resources',
    10,
    true
  ),
  (
    'AI 工具库',
    'tools',
    '/tools',
    '从资源库中以工具视角筛选可用的海外 AI 工具。',
    'AI 工具库',
    'AI TOOL LIBRARY',
    '这是资源库的工具视角，优先筛选通用助手、AI 搜索、知识库、设计、图片、视频、音频和开发类工具。',
    'AI 工具库',
    '从资源库中按工具视角筛选可用的海外 AI 工具、创作工具、搜索工具和开发资源。',
    '工具内容暂无发布',
    '在后台新增内容，并选择发布位置“AI工具页”后，这里会自动展示。',
    '进入资源库',
    '/resources',
    'tools',
    20,
    true
  ),
  (
    'AI 工作流',
    'workflows',
    '/workflows',
    '沉淀 AI 内容创作、资料整理、自动化发布和工程数字化的可复用工作流。',
    'AI 工作流',
    'WORKFLOWS',
    '这里展示后台发布到“工作流页”的内容，用来沉淀可复用的 AI 内容生产、资料整理、自动化和工程数字化流程。',
    'AI 工作流',
    '沉淀 AI 内容创作、资料整理、自动化发布和工程数字化的可复用工作流。',
    '工作流内容正在搭建',
    '在后台新增内容，并选择发布位置“工作流页”后，这里会自动展示。',
    '发布工作流',
    '/admin?section=content-publish',
    'workflows',
    30,
    true
  ),
  (
    'AI 教程',
    'tutorials',
    '/tutorials',
    'AI 工具教程、TikTok AI 运营、工程 AI 应用和产品化实验的内容入口。',
    'AI 教程',
    'TUTORIALS',
    '这里展示后台发布到“教程页”的内容，后续可扩展为文章、视频、附件和工作流步骤混合的 CMS 内容页。',
    'AI 教程',
    'AI 工具教程、TikTok AI 运营、工程 AI 应用和产品化实验的内容入口。',
    '教程内容正在搭建',
    '在后台新增内容，并选择发布位置“教程页”后，这里会自动展示。',
    '发布教程',
    '/admin?section=content-publish',
    'tutorials',
    40,
    true
  ),
  (
    'AI 新手路线',
    'roadmap',
    '/roadmap',
    '面向 AI 新手、TikTok AI 运营、工程 AI 应用和未来 SaaS 实验的学习路线入口。',
    'AI 新手路线',
    'ROADMAP',
    '这个页面展示后台发布到“新手路线页”的内容，用来把 AI 学习和应用路径拆成可执行阶段。',
    'AI 新手路线',
    '面向 AI 新手、TikTok AI 运营、工程 AI 应用和未来 SaaS 实验的学习路线入口。',
    '路线内容暂无发布',
    '在后台新增内容，并选择发布位置“新手路线页”后，这里会自动展示。',
    '发布路线内容',
    '/admin?section=content-publish',
    'roadmap',
    50,
    true
  )
on conflict (slug) do update set
  title = excluded.title,
  page_path = excluded.page_path,
  description = excluded.description,
  hero_title = excluded.hero_title,
  hero_subtitle = excluded.hero_subtitle,
  hero_description = excluded.hero_description,
  seo_title = excluded.seo_title,
  seo_description = excluded.seo_description,
  empty_state_title = excluded.empty_state_title,
  empty_state_description = excluded.empty_state_description,
  primary_cta_text = excluded.primary_cta_text,
  primary_cta_href = excluded.primary_cta_href,
  placement_slug = excluded.placement_slug,
  sort_order = excluded.sort_order,
  is_active = excluded.is_active;
